openapi: 3.0.2
info:
    title: Globex Partners API Gateway
    version: 1.0.0
    description: Globex APIs made accessible to global partners to view Globex's catalog and products
paths:
    /partners/services/product:
        summary: Get a paginated list of products
        description: Get a paginated list of products
        get:
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/paginatedProductList'
                    description: Product list found.
            description: Get a paginated list of products
        parameters:
            -
                name: page
                description: The page number. First page is 1.
                schema:
                    type: integer
                in: query
            -
                name: limit
                description: The maximum number of products returned.
                schema:
                    type: integer
                in: query
            -
                name: inventory
                description: Whether to include inventory information.
                schema:
                    type: boolean
                in: query
    '/partners/services/product/{id}':
        summary: Get product by id
        description: Get product by id
        get:
            parameters:
                -
                    name: inventory
                    description: 'If true, include inventory information'
                    schema:
                        type: boolean
                    in: query
                    required: false
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/product'
                    description: Product found
                '404':
                    description: Product not found
            summary: Get product by id
            description: Get product by id
        parameters:
            -
                name: id
                schema:
                    type: string
                in: path
                required: true
    '/partners/services/product/list/{ids}':
        summary: Get product list by ids
        description: Get product list by ids
        get:
            parameters:
                -
                    name: inventory
                    description: Whether to include inventory information
                    schema:
                        type: boolean
                    in: query
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/product'
                    description: product list found
            summary: Get product list
            description: Get product list
        parameters:
            -
                name: ids
                description: comma separated list of product ids
                schema:
                    type: string
                in: path
                required: true
    '/partners/services/product/category/{categories}':
        summary: Get products by categories
        description: Return the list of products that belong to the given categories.
        get:
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/product'
                    description: Product list found.
            summary: Get products by category
        parameters:
            -
                name: categories
                description: Comma separated list of category names.
                schema:
                    type: string
                in: path
                required: true
            -
                name: inventory
                description: Whether to include inventory information.
                schema:
                    type: boolean
                in: query
    '/partners/services/product/tag/{tags}':
        summary: Get products by tags
        description: Return the list of products that are tagged with he given tags.
        get:
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/product'
                    description: Product list found.
            summary: Get products by tag
        parameters:
            -
                name: inventory
                description: Whether to include inventory information.
                schema:
                    type: boolean
                in: query
            -
                name: tags
                description: Comma separated list of tags
                schema:
                    type: string
                in: path
                required: true
components:
    schemas:
        product:
            description: ''
            type: object
        paginatedProductList:
            title: Root Type for paginated-product-list
            description: ''
            type: object
    responses:
        paginated-product-list:
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/paginatedProductList'
                    examples:
                        paginated-product-list-with-inventory:
                            value:
                                content:
                                    -
                                        itemId: '329299'
                                        name: Quarkus T-shirt
                                        desc: >-
                                            Our T-Shirt is an everyday essential! This short-sleeve
                                            heavyweight T-shirt is comfortable, economical and made to last.
                                            Designed with a traditional fit that runs true to size, he’ll show
                                            off his personality, humor and interests with an easy, relaxed
                                            style.
                                        price: 10
                                        quantity: 736
                                    -
                                        itemId: '329199'
                                        name: Pronounced Kubernetes
                                        desc: >-
                                            Our Men's Value T-Shirt is an everyday essential! This
                                            short-sleeve heavyweight T-shirt is comfortable, economical and
                                            made to last. Designed with a traditional fit that runs true to
                                            size, he’ll show off his personality, humor and interests with an
                                            easy, relaxed style.
                                        price: 9
                                        quantity: 512
                                pageable:
                                    sort:
                                        sorted: false
                                        unsorted: true
                                        empty: true
                                    offset: 0
                                    pageNumber: 0
                                    pageSize: 5
                                    paged: true
                                    unpaged: false
                                totalPages: 9
                                totalElements: 41
                                last: false
                                size: 5
                                number: 0
                                sort:
                                    sorted: false
                                    unsorted: true
                                    empty: true
                                numberOfElements: 5
                                first: true
                                empty: false
                        paginated-product-list-without-inventory:
                            value:
                                content:
                                    -
                                        itemId: '329299'
                                        name: Quarkus T-shirt
                                        desc: >-
                                            Our T-Shirt is an everyday essential! This short-sleeve
                                            heavyweight T-shirt is comfortable, economical and made to last.
                                            Designed with a traditional fit that runs true to size, he’ll show
                                            off his personality, humor and interests with an easy, relaxed
                                            style.
                                        price: 10
                                    -
                                        itemId: '329199'
                                        name: Pronounced Kubernetes
                                        desc: >-
                                            Our Men's Value T-Shirt is an everyday essential! This
                                            short-sleeve heavyweight T-shirt is comfortable, economical and
                                            made to last. Designed with a traditional fit that runs true to
                                            size, he’ll show off his personality, humor and interests with an
                                            easy, relaxed style.
                                        price: 9
                                pageable:
                                    sort:
                                        sorted: false
                                        unsorted: true
                                        empty: true
                                    offset: 0
                                    pageNumber: 0
                                    pageSize: 5
                                    paged: true
                                    unpaged: false
                                totalPages: 9
                                totalElements: 41
                                last: false
                                size: 5
                                number: 0
                                sort:
                                    sorted: false
                                    unsorted: true
                                    empty: true
                                numberOfElements: 5
                                first: true
                                empty: false
            description: |-
                API to get product details.
                - get Paginated list of Products
                - get Product details based on comma separated ids
                - get Product detail of a specific product id
        product:
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/product'
                        description: Product Details by Id
                    examples:
                        product-with-inventory:
                            value:
                                itemId: '329299'
                                name: Quarkus T-shirt
                                desc: >-
                                    Our T-Shirt is an everyday essential! This short-sleeve heavyweight
                                    T-shirt is comfortable, economical and made to last. Designed with a
                                    traditional fit that runs true to size, he’ll show off his personality,
                                    humor and interests with an easy, relaxed style.
                                price: 10
                                quantity: 736
                        product-without-inventory:
                            value:
                                itemId: '329299'
                                name: Quarkus T-shirt
                                desc: >-
                                    Our T-Shirt is an everyday essential! This short-sleeve heavyweight
                                    T-shirt is comfortable, economical and made to last. Designed with a
                                    traditional fit that runs true to size, he’ll show off his personality,
                                    humor and interests with an easy, relaxed style.
                                price: 10
            description: Product Details by Id
        product-list:
            content:
                application/json:
                    schema:
                        type: array
                        items:
                            $ref: '#/components/schemas/product'
                            description: Product by list of Ids
                    examples:
                        product-list-with-inventory:
                            value:
                                -
                                    itemId: '329299'
                                    name: Quarkus T-shirt
                                    desc: >-
                                        Our T-Shirt is an everyday essential! This short-sleeve heavyweight
                                        T-shirt is comfortable, economical and made to last. Designed with a
                                        traditional fit that runs true to size, he’ll show off his
                                        personality, humor and interests with an easy, relaxed style.
                                    price: 10
                                    quantity: 736
                                -
                                    itemId: '329199'
                                    name: Pronounced Kubernetes
                                    desc: >-
                                        Our Men's Value T-Shirt is an everyday essential! This short-sleeve
                                        heavyweight T-shirt is comfortable, economical and made to last.
                                        Designed with a traditional fit that runs true to size, he’ll show off
                                        his personality, humor and interests with an easy, relaxed style.
                                    price: 9
                                    quantity: 512
                        product-list-without-inventory:
                            value:
                                -
                                    itemId: '329299'
                                    name: Quarkus T-shirt
                                    desc: >-
                                        Our T-Shirt is an everyday essential! This short-sleeve heavyweight
                                        T-shirt is comfortable, economical and made to last. Designed with a
                                        traditional fit that runs true to size, he’ll show off his
                                        personality, humor and interests with an easy, relaxed style.
                                    price: 10
                                -
                                    itemId: '329199'
                                    name: Pronounced Kubernetes
                                    desc: >-
                                        Our Men's Value T-Shirt is an everyday essential! This short-sleeve
                                        heavyweight T-shirt is comfortable, economical and made to last.
                                        Designed with a traditional fit that runs true to size, he’ll show off
                                        his personality, humor and interests with an easy, relaxed style.
                                    price: 9
            description: List of products
    securitySchemes:
        openid-connect:
            openIdConnectUrl: <replace-me>
            type: openIdConnect
            description: OpenID Connect security scheme
